% CRD checking at this point
clc;clear;close;
crd_source = 'starlette_apr5_pass4.npt';
fidcrd = fopen(crd_source);
[station,stationepochtimescale,target,cosparid,sicid,...
    noradid,spaceepochtimescale,targettype,datatype,...
    year,month,day,hour,minute,sec,endyear,endmonth,...
    endday,endhour,endminute,endsec, refcorrect, cmcorrect,...
    recampcorrect,stsysdelcorrect,satsysdelcorrect,...
    rngtypeind,dataqual,endofsession,endoffile,...
    rangerecord,normrecord,metdata,usedwavelngth,pointing_data] = crd_parse(fidcrd);
rngtypeind
usedwavelngth